services:
  app:
    build:
      context: ./MirageUI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./MirageUI:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev

  backoffice:
    build:
      context: ./backoffice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backoffice:/backoffice
      - /backoffice/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    command: yarn dev

  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./node-server:/node-server
      - /node-server/node_modules
    environment:
      - NODE_ENV=development
    command: node src/server.js