services:
  app:
    build:
      context: ./MirageUI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: yarn dev
    develop:
      watch:
        - action: sync
          path: ./MirageUI
          target: /app
          ignore:
            - node_modules/

  backoffice:
    build:
      context: ./backoffice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    command: yarn dev
    develop:
      watch:
        - action: sync
          path: ./backoffice
          target: /backoffice
          ignore:
            - node_modules/

  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    command: node src/server.js
    develop:
      watch:
        - action: sync
          path: ./node-server
          target: /node-server
          ignore:
            - node_modules/