services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev

  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./node-server:/node-server
      - /node-server/node_modules
    environment:
      - NODE_ENV=development
    command: node src/server.js