services:
  backoffice:
    build:
      context: ./backoffice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backoffice/src/app/data/types:/backoffice/src/app/data/types
    environment:
      - NODE_ENV=development
    command: yarn dev