services:
  backoffice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/backoffice
      - /backoffice/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev